import { describe, expect, it } from 'vitest';
import {
  LEARNING_CONSULTATION_ANSWER_VERSION,
  LEARNING_CONSULTATION_TURN_PURPOSE_VERSION,
} from './contracts';
import {
  validateAdviceAnswerDocument,
  validateTurnPurposeDocument,
} from './validation';

function proposalAnswer(): unknown {
  return {
    schemaVersion: LEARNING_CONSULTATION_ANSWER_VERSION,
    kind: 'proposal',
    userFacingAnswer: '今の教材を続けつつ、期限を区切る案です。',
    options: [
      {
        title: '継続案',
        strategySummary: '現在の教材を完了してから次へ進む。',
        recommendations: [
          {
            recommendationKind: 'material_sequence',
            materialMention: {
              name: '金のフレーズ',
              whyRelevant: '現在使っている教材だから',
            },
            sequencePosition: 1,
            temporalTarget: { kind: 'month_end', year: 2026, month: 10 },
            rationale: '既知の進捗を活かせる。',
            assumptionRefs: ['a-1'],
            evidenceRefs: ['e-1'],
            uncertainty: 'low',
          },
        ],
        tradeoffs: ['新教材へすぐ移らない'],
      },
    ],
    assumptions: ['現在の教材を継続できる'],
    overallUncertainty: 'low',
  };
}

describe('learning consultation strict output validation', () => {
  it('accepts an isolated high-level turn purpose document', () => {
    expect(validateTurnPurposeDocument({
      schemaVersion: LEARNING_CONSULTATION_TURN_PURPOSE_VERSION,
      kind: 'learning_consultation',
    })).toEqual({
      ok: true,
      value: {
        schemaVersion: LEARNING_CONSULTATION_TURN_PURPOSE_VERSION,
        kind: 'learning_consultation',
      },
    });
  });

  it('rejects extra turn-purpose authority fields', () => {
    const result = validateTurnPurposeDocument({
      schemaVersion: LEARNING_CONSULTATION_TURN_PURPOSE_VERSION,
      kind: 'learning_consultation',
      planningIntent: 'create_plan',
    });
    expect(result.ok).toBe(false);
  });

  it('accepts a proposal with bounded evidence and assumption refs', () => {
    const result = validateAdviceAnswerDocument(proposalAnswer(), {
      allowedEvidenceRefs: ['e-1'],
      allowedAssumptionRefs: ['a-1'],
    });
    expect(result.ok).toBe(true);
  });

  it('rejects formal material identity generated by the answer model', () => {
    const answer = proposalAnswer() as {
      options: Array<{ recommendations: Array<{ materialMention: Record<string, unknown> }> }>;
    } & Record<string, unknown>;
    answer.options[0].recommendations[0].materialMention.materialId = 'material-123';

    const result = validateAdviceAnswerDocument(answer, {
      allowedEvidenceRefs: ['e-1'],
      allowedAssumptionRefs: ['a-1'],
    });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errors.join('\n')).toContain('unexpected authority field');
  });

  it('rejects evidence references that were not supplied to the answer purpose', () => {
    const answer = proposalAnswer() as {
      options: Array<{ recommendations: Array<{ evidenceRefs: string[] }> }>;
    } & Record<string, unknown>;
    answer.options[0].recommendations[0].evidenceRefs = ['e-invented'];

    const result = validateAdviceAnswerDocument(answer, {
      allowedEvidenceRefs: ['e-1'],
      allowedAssumptionRefs: ['a-1'],
    });
    expect(result.ok).toBe(false);
  });

  it('keeps clarification exclusive from proposal payload', () => {
    const result = validateAdviceAnswerDocument({
      schemaVersion: LEARNING_CONSULTATION_ANSWER_VERSION,
      kind: 'clarification',
      userFacingAnswer: 'どちらの試験を基準にしますか？',
      requestedMeaning: 'target_exam',
      whyItMatters: '期限が変わるため',
      allowedUnknown: true,
      options: [],
    });
    expect(result.ok).toBe(false);
  });

  it('keeps explanation free of strategy mutation fields', () => {
    const result = validateAdviceAnswerDocument({
      schemaVersion: LEARNING_CONSULTATION_ANSWER_VERSION,
      kind: 'explanation',
      userFacingAnswer: 'この順番にした理由です。',
      rationale: '基礎から積み上げるため',
      assumptionRefs: [],
      evidenceRefs: [],
      tradeoffs: [],
      historical: false,
      recommendations: [],
    });
    expect(result.ok).toBe(false);
  });
});
